config/routes.rb
Stc::Application.routes.draw do
  devise_for :users

  resources :users

  resources :petitions

  resources :events do
    member do
      get :public_show
      get :public_apply
      get :apply
    end
  end

  get '/contacts/all/34kjnxnh2c894545yct4582ct259c8ytc', to: 'home#index_contactos'

  post "/contacto/", to: "home#contacto"

  get '/evento/aspectos-contables-y-legales-al-formar-una-empresa', to: 'events#clase1', as: 'clase1'
  get '/evento/partir-empresa-limitada-o-por-acciones', to: 'events#clase13marzo' # alias de clase13marzo
  get '/evento/partir-empresa-ltda-o-spa', to: 'events#clase13marzo', as: 'clase13marzo'
  get '/evento/comenzar-negocio-de-importaciones-en-chile', to: 'events#clase27marzo', as: 'clase27marzo'

  get '/auth/:provider/callback', to: 'sessions#auth_callback'

  scope "/clases-presenciales" do
    get "13-de-marzo", to: "clases_presenciales#marzo13"
    get "27-de-marzo", to: "clases_presenciales#marzo27"
  end

  root :to => "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, Event
      can :read, User, id: user.id
      can :manage, Petition, user_id: user.id
      can :manage, AuthProvider, user_id: user.id
    end
  end
end

app/models/auth_provider.rb
class AuthProvider < ActiveRecord::Base
	belongs_to :user	
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :petitions
  has_many :users, through: :petitions

  class << self
    def upcoming_for city
      Event.where(city: city).where("\"when\" >= ?", Time.now.beginning_of_day)
    end
  end

  def apply user
    raise Application::AlreadyAppliedError if self.petitions.where(user_id: user.id).any?
    self.petitions.create(
      user_id: user.id,
      status: "requested"
    )
  end
end

app/models/petition.rb
# I whould have named this 'application', but Rails wouldn't let me
class Petition < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :trackable

  has_many :auth_providers, dependent: :destroy
  has_many :petitions, dependent: :destroy

  def add_auth_provider(h)
    raise "Invalid auth hash" unless h
    # if the user already has this provider linked
    existing_provider = self.auth_providers.where( 'ap_name = ?', h[:ap_name] ).first
    existing_provider.destroy if existing_provider
    self.auth_providers.create(
      :ap_name => h[:ap_name],
      :ap_uid => h[:uid], 
      :ap_uname => h[:uname], 
      :ap_uemail => h[:uemail],
      :ap_upicture => h[:upicture],
      :ap_uprofile => h[:uprofile],
      :raw => h[:raw])
    if self.auth_providers.count == 1
      # If this is this user's only auth provider, we set his username and avatar
      self.picture = h[:upicture]
      self.email = h[:uemail]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :log_request

  def log_request
  	Rails.logger.info "Session keys: [#{session.keys.join(", ")}]"
  	Rails.logger.info "Request keys: [#{params.keys.join(", ")}]"
  end
end

app/controllers/clases_presenciales_controller.rb
class ClasesPresencialesController < ApplicationController
  layout false
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  rescue_from Application::EventNotFoundError, with: :event_not_found
  rescue_from Application::EventExpiredError, with: :event_expired
  before_filter :load_event, only: [:public_apply, :public_show]
  load_and_authorize_resource only: [:index, :show, :edit, :update, :new]

  def public_show
    session[:applying_to] = nil
    render layout: "public"
  end

  def public_apply
    session[:applying_to] = @event.id
    render layout: "public"
  end

  def update
    if @event.update(event_params)
      redirect_to(@event)
    else
      render "edit"
    end
  end

  def create
    @event = Event.new(event_params)
    authorize! :create, @event
    if @event.save
      redirect_to event_path(@event)
    else
      render "new"
    end
  end

  def apply
    redirect_to "/auth/linkedin" and return unless user_signed_in?
    redirect_to public_show_event_path(session[:applying_to])
    Event.find(session[:applying_to]).apply(current_user)
    session[:applying_to] = nil
    flash[:notice] = "You have applied successfully. You will receive an email shortly from our team"
  rescue Application::AlreadyAppliedError
    flash[:error] = "You already applied to this event."
  end

  private

  def event_params
    params.require(:event).permit(:when, :duration, :address, :city, :country, :name, :description, :picture, :price)
  end

  def event_not_found
    render text: "Evento no encontrado!", status: 404
  end

  def event_expired
    render text: "Evento expirado!", status: 404
  end

  def load_event
    @event = Event.where(id: params[:id]).first
    raise Application::EventNotFoundError unless @event
    raise Application::EventExpiredError unless @event.when > Time.now.beginning_of_day
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "public"
  
  def contacto
  	@c = Contact.new(contact_params)
  	@c.save!
  	render text: "OK"
  end

  def index_contactos
    @contacts = Contact.all
    render 'contacts/index', layout: false
  end

  def contact_params
  	params.require(:contact).permit(:user, :email, :phone, :event, :comment, :code, :referer)
  end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  load_and_authorize_resource only: [:index]
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def auth_callback
		provider = params[:provider]
		omniauth = request.env['omniauth.auth']
		Rails.logger.debug omniauth.to_yaml

		# continue only if hash and parameter exist
		return if omniauth.nil? or provider.nil?
				
		h = auth_provider_hash omniauth

		auth = AuthProvider.find_by_ap_name_and_ap_uid(provider, h[:uid])
		Rails.logger.debug "Auth provider found for user #{auth.user_id}" if auth
		Rails.logger.debug "No auth provider found for [#{provider}-#{h[:uid]}]" if auth.nil?

		if user_signed_in?
			# if this authentication provider is not linked to the account, add it
			if !auth
				current_user.add_auth_provider h
			else
				# Already added, do nothing
			end
		else
			# check if user has already signed in using this authentication provider and continue with sign in process if yes
			if auth
				sign_in auth.user
			else
				# at this point we are facing a new user... so he must be signing up
				Rails.logger.debug "Unknown user trying to log in"
				user = User.new
				user.save!
				user.add_auth_provider h
				sign_in user
			end
		end
		if session[:applying_to]
			redirect_to apply_event_path(session[:applying_to]) and return
		end
		redirect_to root_path
	end

	def auth_provider_hash omniauth
		hash = {}
		hash[:raw] = omniauth.to_xml
		hash[:uid] = omniauth['uid']
		hash[:uemail] = omniauth['info']['email']
		hash[:uname] = omniauth['info']['nickname']
		hash[:uprofile] = omniauth['info']['urls']['public_profile']
		hash[:upicture] = omniauth['info']['image']
		hash[:ap_name] = omniauth['provider']
		hash
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource only: [:index, :show, :edit, :update]

  def show
    @linkedin = @user.auth_providers.where(ap_name: "linkedin").first
  end

  def update
    if @user.update(user_params)
      redirect_to(@user)
    else
      render "edit"
    end
  end

  def user_params
    params.require(:user).permit(:email, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/index.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Contactos
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} StartClass
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{href: root_path} Home

    .container
      .row
        .col-md-12
          %table.table.table.table-striped
            %tr
              %th ID
              %th Fecha
              %th Usuario
              %th Teléfono
              %th Email
              %th Interés en Curso
              %th Comentario
              %th Código descuento
              %th Recomendador
            - @contacts.each do |j|
              %tr
                %td= j.id
                %td= j.created_at
                %td= j.user
                %td= j.phone
                %td= j.email
                %td= j.event
                %td= j.comment
                %td= j.code
                %td= j.referer

app/views/events/_form.html.haml
= form_for @event, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :when, :class => 'control-label'
    .controls
      = f.text_field :when, :class => 'text_field'
  .control-group
    = f.label :duration, :class => 'control-label'
    .controls
      = f.text_field :duration, :class => 'text_field'
  .control-group
    = f.label :address, :class => 'control-label'
    .controls
      = f.text_field :address, :class => 'text_field'
  .control-group
    = f.label :city, :class => 'control-label'
    .controls
      = f.text_field :city, :class => 'text_field'
  .control-group
    = f.label :country, :class => 'control-label'
    .controls
      = f.text_field :country, :class => 'text_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :picture, :class => 'control-label'
    .controls
      = f.text_field :picture, :class => 'text_field'
  .control-group
    = f.label :price, :class => 'control-label'
    .controls
      = f.text_field :price, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn'

app/views/events/clase13marzo.html.haml
- content_for :titulo_html do
  Curso LTDA vs. SPA / STARTCLASS

- content_for :titulo_visible do
  13-mar / 19:45 / centro de eventos vitacura

- content_for :nombre_curso do
  SRL vs. SPA

- content_for :encabezado do
  %h1 ¿sociedad de responsabilidad limitada o por acciones?
  %h2 tipos de sociedad / esquemas de participación / constitución e inicio de actividades

- content_for :url_mapa do
  https://mapsengine.google.com/map/u/0/embed?mid=z0umjk9nG7zM.k5UyS7WRDpH0

- content_for :cuando_donde_quien do
  %p.h3
    %strong Cuándo:
    Jueves 13 de marzo 2014 de 19:45 a 22:00 hrs.
  %p.h3
    %strong Dónde:
    Centro de Eventos Vitacura, San Félix 1318, Vitacura
  %p.h3
    %strong Expone:
    Alan Krausz

- content_for :fecha_precio do
  .date
    %p
      13
      %span MAR
  .democont
    %ul.demo-tags
      %li
        %a.inscribirse{href: "#"} $25.000
    .bullets.row
      .bullet
        %span.glyphicon.glyphicon-ok
        ="(- $4.000) por cada amigo inscrito"
      .bullet
        %span.glyphicon.glyphicon-ok
        Quedas conforme o tu dinero de vuelta

- content_for :temario do
  %p
    En este curso aprenderás a elegir el tipo de sociedad que mejor se adapte a tu negocio y conocer sus diferencias. Entregaremos los conocimientos legales para constituir y operar una empresa. Se revisarán las distintas clases de sociedades (EIRL, SpA, Ltda, entre otras) y se mostrarán los beneficios a largo plazo de cada sociedad, dependiendo si esperas tener inversionistas o no. Además, se revisarán las obligaciones tributarias que implica tener una empresa.
  %h4 tipos de sociedad y esquemas de participación
  %ul
    %li ¿Por qué una sociedad? Cuándo no conviene / no aplica la persona natural.
    %li Tipos de sociedad. Sociedades de personas y de capital. EIRL, LTDA, SpA, SA. Similitudes y diferencias.
    %li Acuerdos de participación. Acciones. Protección para los socios y la empresa.
    %li Estructura de una empresa. Accionistas, directorio, administración, etc.
    %li Riesgos del Negocio
  %h4 constitución de sociedad e iniciación de actividades
  %ul
    %li Cómo constituir una sociedad.
    %li Checklist para constitución vía Internet: requisitos, limitaciones, costos y plazos.
    %li Checklist para constitución presencial: actores, papeles, costos y plazos.
    %li Otros requisitos para iniciar actividades. RUT, patente, permisos. Actores, papeles, costos y plazos.
    %li Valor de toda la operación

- content_for :instructor_1 do
  = image_tag "mugshot-ak.jpg"
  %h3 Alan Krausz
  %ul.text-left
    %li Abogado Universidad de Chile; Master en Business Law Universidad Adolfo Ibáñez
    %li Especialista en Derecho del Consumidor, Derecho Civil, Comercial y Económico
    %li Profesor "Derecho y Empresa" Universidad Adolfo Ibáñez
    %li
      Fundador de
      = link_to "Kawell", "http://www.kawell.cl/"

- content_for :script do
  :plain

app/views/events/clase27marzo.html.haml
- content_for :titulo_html do
  Curso importaciones / STARTCLASS

- content_for :titulo_visible do
  Curso importaciones

- content_for :nombre_curso do
  importaciones

- content_for :encabezado do
  %h1 comenzando un negocio de importaciones en chile
  %h2 Necesidad, Proveedores, Transporte, Internacion


- content_for :cuando_donde_quien do
  %p.h3
    %strong Cuándo:
    Próximamente

- content_for :fecha_precio do
  &nbsp;

- content_for :temario do
  %p
    Curso para emprendedores con o sin conocimiento en comercio internacional que deseen generar ingresos a través de un exitoso negocio de importaciones.
  %h4 Necesidad, Proveedores, Transporte, Internacion
  %ul
    %li Qué necesita nuestro mercado. Por qué ese producto?
    %li Búsqueda y selección del proveedor
    %li Validación de proveedores y herramientas para minimizar el riesgo
    %li Negociación con el proveedor
    %li Medios de pago para la operación
    %li Consolidación de carga
    %li Selección del transporte (marítimo / aéreo) y contratación de seguros
    %li Tramitación aduanera, retiro de mercancía y roles del Agente de Aduana
    %li Entidades que intervienen en la importación
    %li Costos ocultos de una importación
    %li Tratados de libre comercio e impuesto ad-valorem
    %li Problemas y errores comunes a la hora de importar (esto se puede agregar en cada uno de los temas anteriores)

- content_for :instructor_1 do
  &nbsp;

- content_for :script do
  :plain

app/views/events/edit.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/index.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:when)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:country)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:price)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @events.each do |event|
      %tr
        %td= link_to event.name, event_path(event)
        %td= event.when
        %td= event.city
        %td= event.country
        %td= event.address
        %td= event.price
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(event), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_event_path, :class => 'btn btn-primary'

app/views/events/new.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/events/public_show.html.haml
- content_for(:header) do
  %h1.event-name.shadow= @event.name

#slide-event.shadow.slide{"data-stellar-background-ratio" => "0.5"}
  .container.clearfix
    = render "shared/flash"
    .grid_12
      %h1
        #{@event.name}
    .grid_7
      %h2
        #{@event.when.strftime "%Y-%m-%d"} / #{@event.when.strftime "%H:%M"}
      %h2 
        #{@event.address}
      %h2
        #{@event.city}
    .grid_5.omega
      %ul.demo-tags
        %li
          %a{href: "#"}= number_to_currency @event.price, precision: 2
    .grid_7
      = render "shared/event_application", alert_application: false
      %p= @event.description
    .grid_5.omega
      =image_tag @event.picture
    .grid_12
      = render "shared/event_application", alert_application: true
#slide-footer.slide{"data-stellar-background-ratio" => "0.5"}
  .container.footer.clearfix
    .grid_4
      %ul
        %li About us
        %li Santiago office
        %li Bogotá office
        %li Work with us
    .grid_4
      %ul
        %li FAQ
        %li Pricing
        %li Terms & Conditions
        %li Become a partner
    .logo.grid_4.omega
      =image_tag "logo-1-1.png"

= javascript_include_tag "public"
- content_for :script do
  :plain
    //hi!

app/views/events/show.html.haml
- model_class = Event
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:when) + ':'
  %br
  = @event.when
%p
  %strong= model_class.human_attribute_name(:duration) + ':'
  %br
  = @event.duration
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @event.address
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = @event.city
%p
  %strong= model_class.human_attribute_name(:country) + ':'
  %br
  = @event.country
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @event.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @event.description
%p
  %strong= model_class.human_attribute_name(:picture) + ':'
  %br
  = @event.picture
%p
  %strong= model_class.human_attribute_name(:price) + ':'
  %br
  = @event.price

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(@event), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/petitions/_form.html.haml
= form_for @petition, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :event_id, :class => 'control-label'
    .controls
      = f.text_field :event_id, :class => 'text_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.text_field :user_id, :class => 'text_field'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), petitions_path, :class => 'btn'

app/views/petitions/edit.html.haml
- model_class = Petition
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/petitions/index.html.haml
- model_class = Petition
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th Event
      %th User
      %th Status
      %th Created At
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @petitions.each do |petition|
      %tr
        %td= link_to petition.event.name, event_path(petition.event)
        %td= link_to petition.user.email, user_path(petition.user)
        %td= petition.status
        %td=l petition.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_petition_path(petition), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), petition_path(petition), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_petition_path, :class => 'btn btn-primary'

app/views/petitions/show.html.haml
- model_class = Petition
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:event_id) + ':'
  %br
  = @petition.event_id
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @petition.user_id
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @petition.status

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), petitions_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_petition_path(@petition), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), petition_path(@petition), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shared/_event_application.html.haml
- if user_signed_in? && @event.users.where(id: current_user.id).any?
  - if alert_application
    You already applied to this event. We will contact you shortly via email.
- else
  = link_to "", public_apply_event_path(@event), class: "apply_with_linkedin"

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :admin, :class => 'control-label'
    .controls
      = f.check_box :admin, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th Email
      %th Administrador
      %th Último login
      %th Primer login
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.email, user_path(user)
        %td= user.admin ? "Sí" : "No"
        %td=l user.last_sign_in_at
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1 Usuario
  = image_tag @user.picture, style: "float: right;"

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:picture) + ':'
  %br
  = @user.picture
%p
  %strong Administrador?
  %br
  = @user.admin ? "Sí" : "No"
%p
  %strong LinkedIn
  %br
  = link_to @linkedin.ap_uname, @linkedin.ap_uprofile
%p
  %strong Postulaciones
  %table.table.table-striped
    %thead
      %tr
        %th
          %em Evento
        %th
          %em Estatus
        %th
          %em Fecha
    %tbody
      - @user.petitions.each do |petition|
        %tr
          %td= link_to petition.event.name, event_path(petition.event)
          %td= petition.status
          %td=l petition.created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'